In [2]:
import pandas as pd
import openpyxl

In [7]:
df = pd.read_csv("Scouting Data.csv")

In [9]:
dfa = df.style.applymap(lambda x : ('color:white;background-color:red' if float(x) == 0.0 else 'color:black;background-color:yellow' if 0 < float(x) <= 10 else 'color:white;background-color:green') if str(x).replace(".", "").isnumeric() else 'color:white;background-color:black', subset = pd.IndexSlice[:, ["Max Auto Points"]])\
              .applymap(lambda x : ('color:white;background-color:red' if float(x) == 0.0 else 'color:black;background-color:yellow' if 0 < float(x) <= 7 else 'color:white;background-color:green') if str(x).replace(".", "").isnumeric() else 'color:white;background-color:black', subset = pd.IndexSlice[:, ["Auto Balance Ability"]])\
              .applymap(lambda x : ('color:white;background-color:red' if float(x) == 0.0 else 'color:black;background-color:yellow' if 0 < float(x) <= 3 else 'color:white;background-color:green') if str(x).replace(".", "").isnumeric() else 'color:white;background-color:black', subset = pd.IndexSlice[:, ["Low Teleop Average"]])\
              .applymap(lambda x : ('color:white;background-color:red' if float(x) == 0.0 else 'color:black;background-color:yellow' if 0 < float(x) <= 3 else 'color:white;background-color:green') if str(x).replace(".", "").isnumeric() else 'color:white;background-color:black', subset = pd.IndexSlice[:, ["Mid Teleop Average"]])\
              .applymap(lambda x : ('color:white;background-color:red' if float(x) == 0.0 else 'color:black;background-color:yellow' if 0 < float(x) <= 5 else 'color:white;background-color:green') if str(x).replace(".", "").isnumeric() else 'color:white;background-color:black', subset = pd.IndexSlice[:, ["High Teleop Average"]])\
              .applymap(lambda x : ('color:white;background-color:red' if float(x) == 0.0 else 'color:black;background-color:yellow' if 0 < float(x) <= 7 else 'color:white;background-color:green') if str(x).replace(".", "").isnumeric() else 'color:white;background-color:black', subset = pd.IndexSlice[:, ["Engage Performance"]])\
              .applymap(lambda x : ('color:white;background-color:blue' if x == "Cube" else 'color:white;background-color:Orange' if x == "Cone" else 'color:white;background-color:Purple') if str(x) != "nan" else 'color:white;background-color:black', subset = pd.IndexSlice[:, ["Manipulator  Type"]])

display(dfa)
dfa.to_excel("Final Data.xlsx")